### ISSUE TITLE
Number of Lanes in the sample dataset

### ISSUE THREAD

**Issue by oroojlooy** [traffic-signal-control/sample-code#1]
I was looking into `data/syn_1x1_uniform_800_1h` data-set and tried to use it with the presslight code. For that, I need to know how many lane are considered in this data-set. I could not find any clue about it. Would you mind letting me know the number of lanes there? Generally, is there any way to find it out by searching only inside the `roadnet` file?

**Comment by Chacha-Chen** [comment]
Sorry I can't remember. But definitely it is defined in the roadnet file. Please refer to the Cityflow document https://cityflow.readthedocs.io/en/latest/  There should be explanations on the roadnet format.

**Comment by oroojlooy** [comment]
Thanks for the reply. 
I failed to find any information about it in the CityFlow documentation. 
Instead of digging more on that, I generated `flow` and `roadnet` files by the generator of the CityFlow and I was able to attach it to `pressLight` and run it. Although, it seems that the env works fine, but the next states are `None`:

```
[{'cur_phase': [1], 'coming_vehicle': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'leaving_vehicle': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}]
number of actions per agent:  len(env.dic_traffic_env_conf['PHASE_LIST']) 4
time: 0.0
Step time:  0.0044324398040771484
ns, r, d, info:  [{'cur_phase': [4], 'coming_vehicle': None, 'leaving_vehicle': None}] [0.0] False [0.0]
```
Do you have any idea why this happens?

**Comment by Chacha-Chen** [comment]
Check roadnet.json

**Comment by Chacha-Chen** [comment]
I think the next states can only be updated after time 1.0

**Comment by oroojlooy** [comment]
After I create the instance of the environment, I call `env.reset()` and it returns the state that looks fine. After that, whenever I call `env.step(action, test_flag=True)`, it returns `None` for both `coming` and `leaving` vehicles.

**Comment by zxsRambo** [comment]
> I was looking into `data/syn_1x1_uniform_800_1h` data-set and tried to use it with the presslight code. For that, I need to know how many lane are considered in this data-set. I could not find any clue about it. Would you mind letting me know the number of lanes there? Generally, is there any way to find it out by searching only inside the `roadnet` file?

Hi, as for the number of lanes, you can refer to the parse_roadnet() in utility.py where the roadnet is parsed and some information about lanes and phases of intersections can be gotten.

**Comment by zxsRambo** [comment]
> After I create the instance of the environment, I call `env.reset()` and it returns the state that looks fine. After that, whenever I call `env.step(action, test_flag=True)`, it returns `None` for both `coming` and `leaving` vehicles.

Maybe caused by the mismatch between the flow and roadnet you generated and the presslight code. If you want to run the presslight, you can firstly test the data provided in presslight.

**Comment by oroojlooy** [comment]
> > I was looking into `data/syn_1x1_uniform_800_1h` data-set and tried to use it with the presslight code. For that, I need to know how many lane are considered in this data-set. I could not find any clue about it. Would you mind letting me know the number of lanes there? Generally, is there any way to find it out by searching only inside the `roadnet` file?
> 
> Hi, as for the number of lanes, you can refer to the parse_roadnet() in utility.py where the roadnet is parsed and some information about lanes and phases of intersections can be gotten.

Thanks for the reply. Where is the `utility.py`?

**Comment by oroojlooy** [comment]
> > After I create the instance of the environment, I call `env.reset()` and it returns the state that looks fine. After that, whenever I call `env.step(action, test_flag=True)`, it returns `None` for both `coming` and `leaving` vehicles.
> 
> Maybe caused by the mismatch between the flow and roadnet you generated and the presslight code. If you want to run the presslight, you can firstly test the data provided in presslight.

It seems that the issue is because of the `test_flag=True`. Once I set it to `True` it works fine. This behavior seems to be expected because of lines:

        if self.fast_compute or test_flag:
            dic_feature["coming_vehicle"] = None
            dic_feature["leaving_vehicle"] = None
            # dic_feature["num_total_veh"] = simulator_state['num_total_veh']
        else:
            dic_feature["coming_vehicle"] = self._get_coming_vehicles(simulator_state)
            dic_feature["leaving_vehicle"] = self._get_leaving_vehicles(simulator_state)
            # print(simulator_state['num_total_veh'])
in the `_update_feature_map(self, simulator_state,test_flag)` function in the `anon_env.py`. So, what is the purpose of the `test_flag` and similarly `fast_compute`?

**Comment by Chacha-Chen** [comment]
I see the problem now.  Because updating all the features would consume time. If some value would not be needed, we prefer not to update those values (query to CityFlow would consume time). That's why the next states would be None unless we set the self.fast_compute to False (when we don't want to run the code faster) or test_flag to True (see the next states values for debugging).

**Comment by oroojlooy** [comment]
I see. So for RL application, `fast_compute` should remain `False`, right?

**Comment by Chacha-Chen** [comment]
Yes only to make it run faster
